# -*- coding: utf-8 -*-
"""calculadora - proj1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSYlyx2s7QNNBLj0bmggHuAEgyFtYU7g
"""

#Objetivos mínimos do código:
#1-input para 2 números / 2-conversor de input para int ou float / 3-4 operações /4-Loop para várias operações  / 4-printar resultado

print('Sinta-se em casa na Calculadora 2000')
#variáveis para loops
y = 0
z = 0
p = 0
while p == 0:
  #números para a operação
  while y == 0:
    n1 = float( input('Insira o primeiro número da operação: '))
    n2 = float( input('Insira o segundo número da operação: '))
    #quebra de loop
    y = 1
    #conversor para float caso int seja digitado
    if n1 == type(int) or n2 == type(int):
      n1 = type(float)
      n2 = type(float)
  #seleção de operação
  while z == 0:
    x = 0
    op1 = input('Qual operação deseja fazer (primeiro com o segundo, nessa ordem)? \n Digite SOMA para somar \n Digite MULT para multiplicar \n Digite DIV para dividir \n Digite EXP para elevar \n  ')
    z = 1
    #varredura para detectar input
    if op1 == 'SOMA':
      print('A soma é igual a: ', n1 + n2)
    elif op1 == 'MULT':
      print('A multiplicação é igual a: ', n1 * n2)
    elif op1 == 'DIV':
      print('A divisão é igual a: ', n1 / n2)
    elif op1 == 'EXP':
      print('A elevação é igual a: ', n1 ** n2)
    #detecção de input inválido
    else:
      print('Operação inválida')
      #retorno ao loop
      z = 0
  while x == 0:
    #input de lopp
    loop = input('Deseja fazer mais operações? \n "Sim ou Não" \n ')
    x = 1
    if loop == 'Sim' or loop == 'sim':
      loop2 = input('Com os mesmos números? \n "Sim ou Não" \n ')
      if loop2 == 'Sim' or loop2 == 'sim':
        y = 1
        z = 0
      elif loop2 == 'Não' or loop2 == 'não' or loop2 == 'nao' or loop2 == 'Nao':
        y = 0
        z = 0
      else:
        print('Resposta inválida')
        x = 0
    else:
      print('Até a próxima!')
      p = 1

